import streamlit as st
import requests
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from fpdf import FPDF
import io

# --- CONFIGURATION ---
API_URL = "http://127.0.0.1:8000"

st.set_page_config(
    page_title="EcoPackAI Dashboard",
    page_icon="🌿",
    layout="wide"
)

# --- INITIALIZE SESSION STATE ---
if 'recommendations' not in st.session_state:
    st.session_state['recommendations'] = None
if 'ran_search' not in st.session_state:
    st.session_state['ran_search'] = False
if 'all_materials' not in st.session_state:
    st.session_state['all_materials'] = []

# --- HELPER: FETCH DATA FOR BI DASHBOARD ---
# We need this to populate the dropdowns in the Analytics tab
def load_all_materials():
    if not st.session_state['all_materials']:
        try:
            # We fetch a broad list by asking for "Logistics" which usually has many materials
            payload = {"industry": "Logistics", "priority_eco": 1, "priority_cost":1, "priority_strength":1}
            resp = requests.post(f"{API_URL}/recommend", json=payload)
            if resp.status_code == 200:
                st.session_state['all_materials'] = resp.json().get("top_recommendations", [])
        except:
            pass

# --- HELPER: PDF GENERATOR ---
def create_pdf(current_mat, new_mat, quantity, savings_cost, savings_co2):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="EcoPackAI - Sustainability Report", ln=True, align='C')
    
    pdf.set_font("Arial", size=12)
    pdf.ln(10)
    pdf.cell(200, 10, txt=f"Comparison: {current_mat['material_name']} vs. {new_mat['material_name']}", ln=True, align='L')
    pdf.cell(200, 10, txt=f"Annual Usage: {quantity} units", ln=True, align='L')
    
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="Projected Impact (12 Months):", ln=True, align='L')
    
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Total Cost Savings: {savings_cost:.2f} INR", ln=True, align='L')
    pdf.cell(200, 10, txt=f"Total CO2 Reduction: {savings_co2:.2f} Points (Index)", ln=True, align='L')
    
    pdf.ln(20)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(200, 10, txt="Generated by EcoPackAI Intelligent System", ln=True, align='C')
    
    return pdf.output(dest='S').encode('latin-1')

# --- CUSTOM CSS ---
st.markdown("""
    <style>
    .main { background-color: #f8f9fa; }
    .stButton>button { width: 100%; border-radius: 5px; height: 3em; background-color: #198754; color: white; }
    .stButton>button:hover { background-color: #157347; color: white; border: none; }
    
    /* FIX: Force text color to be dark inside the cards */
    .metric-card { 
        background-color: white; 
        padding: 20px; 
        border-radius: 10px; 
        box-shadow: 0 2px 4px rgba(0,0,0,0.1); 
        text-align: center; 
        color: #212529 !important; /* Force dark text */
    }
    .metric-card h3 { color: #198754 !important; } /* Green Headers */
    .metric-card p { color: #212529 !important; } /* Dark Paragraphs */
    
    h1 { color: #0f5132; }
    h2, h3 { color: #198754; }
    </style>
    """, unsafe_allow_html=True)

# --- HEADER ---
col_head1, col_head2 = st.columns([1, 5])
with col_head1:
    st.image("https://cdn-icons-png.flaticon.com/512/3209/3209968.png", width=80) 
with col_head2:
    st.title("EcoPackAI Intelligence System")
    st.markdown("##### 🚀 AI-Powered Sustainable Packaging Recommendations & Analytics")

st.divider()

# --- SIDEBAR NAVIGATION ---
st.sidebar.header("Navigation")
# UPDATED: Added 3rd Option for BI Dashboard
page = st.sidebar.radio("Go to Module:", ["🔍 Recommendation Engine", "🤖 AI Impact Predictor", "📊 BI Analytics & Reports"])

# ==============================================================================
# MODULE 1: RECOMMENDATION ENGINE
# ==============================================================================
if page == "🔍 Recommendation Engine":
    st.header("🔍 Find the Perfect Material")
    
    col1, col2 = st.columns([1, 2])
    
    with col1:
        st.subheader("1. Define Priorities")
        with st.form("recommendation_form"):
            industry = st.selectbox("Select Industry", 
                ["Electronics", "Food", "Cosmetics", "Logistics", "Construction"])
            
            st.write("---")
            st.write("**Adjust Importance Weights**")
            
            w_eco = st.slider("🌱 Sustainability", 0.0, 1.0, 0.6)
            w_cost = st.slider("💰 Cost Efficiency", 0.0, 1.0, 0.2)
            w_strength = st.slider("💪 Durability", 0.0, 1.0, 0.2)
            
            submit_btn = st.form_submit_button("🔎 Analyze & Recommend")
    
    if submit_btn:
        payload = {
            "industry": industry,
            "priority_eco": w_eco,
            "priority_cost": w_cost,
            "priority_strength": w_strength
        }
        
        try:
            with st.spinner(f'🤖 AI is analyzing database for {industry} materials...'):
                response = requests.post(f"{API_URL}/recommend", json=payload)
            
            if response.status_code == 200:
                data = response.json()
                st.session_state['recommendations'] = data.get("top_recommendations", [])
                st.session_state['ran_search'] = True
                # Also save to all_materials for the BI tab
                st.session_state['all_materials'] = st.session_state['recommendations']
            else:
                st.error(f"❌ API Error: {response.status_code}")
                
        except Exception as e:
            st.error(f"❌ Connection Failed: {e}")

    with col2:
        if st.session_state['ran_search'] and st.session_state['recommendations']:
            results = st.session_state['recommendations']
            st.success(f"✅ Found {len(results)} optimal matches!")
            
            df = pd.DataFrame(results)
            
            # HIGHLIGHT CARD
            best_mat = df.iloc[0]
            st.markdown(f"""
            <div class="metric-card">
                <h3>🏆 Top Recommendation: {best_mat['material_name']}</h3>
                <p>Score: <strong>{best_mat['final_score']:.2f}</strong> | Price: <strong>₹{best_mat['price_inr_per_unit']}</strong> | CO₂ Score: <strong>{best_mat['co2_emission_score']}</strong></p>
            </div>
            """, unsafe_allow_html=True)
            st.write("") 

            # TABLE & DOWNLOAD
            c_table, c_dl = st.columns([3, 1])
            with c_table:
                st.dataframe(
                    df[['material_name', 'final_score', 'price_inr_per_unit', 'co2_emission_score']],
                    use_container_width=True,
                    hide_index=True
                )
            with c_dl:
                csv = df.to_csv(index=False).encode('utf-8')
                st.download_button(
                    label="📄 Download Report",
                    data=csv,
                    file_name=f"ecopack_report.csv",
                    mime="text/csv"
                )

            # CHARTS
            tab_v1, tab_v2 = st.tabs(["📊 Market Analysis", "🕸️ Spider Chart"])
            
            with tab_v1:
                fig = px.scatter(
                    df, x="price_inr_per_unit", y="co2_emission_score",
                    size="final_score", color="material_name",
                    title="Cost vs. Sustainability Trade-off",
                    labels={"price_inr_per_unit": "Price (₹)", "co2_emission_score": "CO₂ Impact"}
                )
                st.plotly_chart(fig, use_container_width=True)
            
            with tab_v2:
                st.markdown("### 🕸️ Material Capabilities")
                target_mat = st.selectbox("Select Material to Visualize", df['material_name'].unique())
                
                row = df[df['material_name'] == target_mat].iloc[0]
                
                r_score = row['final_score'] * 10
                r_co2 = max(0, 10 - row['co2_emission_score']) 
                r_price = max(0, 10 - (row['price_inr_per_unit'] / 50)) 

                fig_radar = go.Figure(go.Scatterpolar(
                    r=[r_score, r_co2, r_price],
                    theta=['Overall Fit', 'Eco-Friendliness', 'Cost Efficiency'],
                    fill='toself',
                    name=target_mat,
                    line_color='#198754'
                ))
                fig_radar.update_layout(polar=dict(radialaxis=dict(visible=True, range=[0, 10])), title=f"Profile: {target_mat}")
                st.plotly_chart(fig_radar, use_container_width=True)

        elif st.session_state['ran_search'] and not st.session_state['recommendations']:
            st.warning("⚠️ No matching materials found.")

# ==============================================================================
# MODULE 2: AI PREDICTOR
# ==============================================================================
elif page == "🤖 AI Impact Predictor":
    st.header("🤖 Material Impact Predictor")
    st.markdown("Use our **Random Forest** & **XGBoost** models to predict properties of theoretical materials.")
    st.write("---")
    
    c1, c2, c3 = st.columns(3)
    with c1: p_strength = st.number_input("Tensile Strength (MPa)", min_value=0.1, value=150.0)
    with c2: p_weight = st.number_input("Weight Capacity (kg)", min_value=0.1, value=500.0)
    with c3: p_type = st.selectbox("Material Type Code", [0, 1, 2], help="0: Natural, 1: Plastic, 2: Metal")

    c4, c5 = st.columns(2)
    with c4: p_bio = st.slider("Biodegradability Score (1-10)", 1, 10, 8)
    with c5: p_recycle = st.slider("Recyclability %", 0, 100, 90)

    st.write("")
    if st.button("🚀 Run Prediction Models"):
        payload = {
            "tensile_strength": p_strength, "weight_capacity": p_weight,
            "biodegradability_score": p_bio, "recyclability_percent": p_recycle,
            "material_type_encoded": p_type
        }
        
        try:
            with st.spinner('Calculating Cost & CO₂...'):
                response = requests.post(f"{API_URL}/predict_impact", json=payload)
            
            if response.status_code == 200:
                data = response.json()
                preds = data["predictions"]
                
                st.write("---")
                st.subheader("🧪 AI Prediction Results")
                
                m1, m2 = st.columns(2)
                with m1:
                    st.markdown(f"""
                    <div class="metric-card">
                        <h4 style="color:#555">💰 Estimated Cost</h4>
                        <h1 style="color:#0d6efd">₹{preds['estimated_cost_inr']}</h1>
                        <p>Confidence: 99% (Random Forest)</p>
                    </div>""", unsafe_allow_html=True)
                
                with m2:
                    st.markdown(f"""
                    <div class="metric-card">
                        <h4 style="color:#555">🌍 Estimated CO₂ Score</h4>
                        <h1 style="color:#ffc107">{preds['estimated_co2_emission']}</h1>
                        <p>Confidence: 99% (XGBoost)</p>
                    </div>""", unsafe_allow_html=True)
                
                fig_gauge = go.Figure(go.Indicator(
                    mode = "gauge+number",
                    value = preds['estimated_co2_emission'],
                    title = {'text': "Environmental Impact Scale"},
                    gauge = {
                        'axis': {'range': [0, 10]},
                        'bar': {'color': "green" if preds['estimated_co2_emission'] < 4 else "orange"},
                        'steps': [{'range': [0, 4], 'color': "#d4edda"}, {'range': [4, 7], 'color': "#fff3cd"}, {'range': [7, 10], 'color': "#f8d7da"}]
                    }
                ))
                st.plotly_chart(fig_gauge, use_container_width=True)
            else:
                st.error("Prediction Failed.")
        except Exception as e:
            st.error(f"Connection Error: {e}")

# ==============================================================================
# MODULE 3: BI ANALYTICS (NEW!)
# ==============================================================================
elif page == "📊 BI Analytics & Reports":
    st.header("📊 Business Intelligence Dashboard")
    st.markdown("Analyze the financial and environmental impact of switching materials.")
    
    # Try to load data if list is empty
    load_all_materials()
    
    if not st.session_state['all_materials']:
        st.warning("⚠️ Please run a search in the 'Recommendation' tab first to load materials.")
    else:
        # DATA PREPARATION
        df_all = pd.DataFrame(st.session_state['all_materials'])
        names = df_all['material_name'].tolist()
        
        c1, c2, c3 = st.columns(3)
        with c1:
            current_name = st.selectbox("🔻 Current Material (Baseline)", names, index=len(names)-1)
        with c2:
            new_name = st.selectbox("✅ Proposed Material (Switch)", names, index=0)
        with c3:
            annual_qty = st.number_input("📅 Annual Usage (Units)", min_value=100, value=10000, step=100)
            
        # GET DATA FOR SELECTION
        cur_row = df_all[df_all['material_name'] == current_name].iloc[0]
        new_row = df_all[df_all['material_name'] == new_name].iloc[0]
        
        # CALCULATIONS
        cost_diff = (cur_row['price_inr_per_unit'] - new_row['price_inr_per_unit']) * annual_qty
        co2_diff = (cur_row['co2_emission_score'] - new_row['co2_emission_score']) * annual_qty
        
        st.write("---")
        
        # 1. KPI CARDS
        kpi1, kpi2, kpi3 = st.columns(3)
        with kpi1:
            st.markdown(f"""<div class="metric-card"><h3>💰 Annual Cost Savings</h3>
            <h2 style="color: {'green' if cost_diff > 0 else 'red'}">₹{cost_diff:,.2f}</h2></div>""", unsafe_allow_html=True)
        with kpi2:
            st.markdown(f"""<div class="metric-card"><h3>🌍 Annual CO₂ Reduction</h3>
            <h2 style="color: green">{co2_diff:,.2f} <small>Points</small></h2></div>""", unsafe_allow_html=True)
        with kpi3:
            pct_change = ((new_row['price_inr_per_unit'] - cur_row['price_inr_per_unit']) / cur_row['price_inr_per_unit']) * 100
            st.markdown(f"""<div class="metric-card"><h3>📉 Cost Change %</h3>
            <h2 style="color: {'green' if pct_change < 0 else 'red'}">{pct_change:.1f}%</h2></div>""", unsafe_allow_html=True)
            
        st.write("")
        
        # 2. CHARTS (Material Usage Trends)
        tab_c1, tab_c2 = st.tabs(["📈 Cumulative Savings Trend", "📊 Unit Comparison"])
        
        with tab_c1:
            # Simulate Month-over-Month trend
            months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
            monthly_savings = np.cumsum([cost_diff/12] * 12)
            
            fig_trend = px.line(x=months, y=monthly_savings, markers=True, 
                                title="Projected Cumulative Savings Over 1 Year",
                                labels={'x': 'Month', 'y': 'Total Savings (₹)'})
            fig_trend.update_traces(line_color='#198754', line_width=4)
            st.plotly_chart(fig_trend, use_container_width=True)
            
        with tab_c2:
            # Side-by-Side Comparison
            comp_data = pd.DataFrame({
                'Metric': ['Price per Unit', 'CO₂ Score'],
                'Current Material': [cur_row['price_inr_per_unit'], cur_row['co2_emission_score']],
                'New Material': [new_row['price_inr_per_unit'], new_row['co2_emission_score']]
            })
            fig_bar = go.Figure(data=[
                go.Bar(name='Current', x=comp_data['Metric'], y=comp_data['Current Material'], marker_color='gray'),
                go.Bar(name='Proposed', x=comp_data['Metric'], y=comp_data['New Material'], marker_color='#198754')
            ])
            fig_bar.update_layout(title="Unit Comparison: Baseline vs Proposed")
            st.plotly_chart(fig_bar, use_container_width=True)

        # 3. EXPORT REPORTS
        st.write("---")
        st.subheader("📑 Export Sustainability Reports")
        
        c_exp1, c_exp2 = st.columns(2)
        
        with c_exp1:
            # PDF EXPORT
            if st.button("📄 Generate PDF Report"):
                pdf_bytes = create_pdf(cur_row, new_row, annual_qty, cost_diff, co2_diff)
                st.download_button(label="📥 Download PDF", data=pdf_bytes, file_name="sustainability_report.pdf", mime="application/pdf")
        
        with c_exp2:
            # EXCEL EXPORT
            excel_data = pd.DataFrame([cur_row, new_row])
            output = io.BytesIO()
            with pd.ExcelWriter(output, engine='openpyxl') as writer:
                excel_data.to_excel(writer, index=False, sheet_name='Comparison_Data')
            st.download_button(label="📊 Download Excel Data", data=output.getvalue(), file_name="material_analysis.xlsx", mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")