### Test GET materials
GET https://packaging-recommendation-system-5.onrender.com/api/materials

### Test POST recommend

POST https://packaging-recommendation-system-5.onrender.com/api/material
Content-Type: application/json



{
  "product_name": "mobile",
  "category": "electronics",
  "weight_kg": 1,
  "fragile": false
}







