CREATE TABLE materials (
    MATERIAL_ID INTEGER PRIMARY KEY,
    MATERIAL_TYPE TEXT,
    STRENGTH REAL,
    WEIGHT_CAPACITY REAL,
    BIODEGRADABILITY_SCORE REAL,
    Co2_EMISSION_SCORE REAL,
    RECYCLABILITY_PERCENTAGE REAL,
    INDUSTRY_CATEGORY TEXT
);

CREATE TABLE products (
    PRODUCT_ID INTEGER,
    PRODUCT_NAME TEXT,
    CATEGORY TEXT,
    WEIGHT REAL,
    FRAGILITY_LEVEL REAL,
    INDUSTRY TEXT
);

