import { useState, useEffect } from 'react';
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar,
  LineChart, Line, Legend, PieChart, Pie, Cell, AreaChart, Area
} from 'recharts';
import { 
  BarChart3, TrendingDown, Recycle, Leaf, DollarSign, Package, 
  Download, FileText, FileSpreadsheet, Printer, Calendar, TrendingUp, Mail
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { getAnalyticsData, packagingMaterials, productCategories } from '@/data/packagingMaterials';
import { toast } from 'sonner';

export const AdvancedDashboard = () => {
  const [analyticsData, setAnalyticsData] = useState<ReturnType<typeof getAnalyticsData> | null>(null);
  const [isExporting, setIsExporting] = useState<'pdf' | 'excel' | null>(null);

  useEffect(() => {
    setAnalyticsData(getAnalyticsData());
  }, []);

  if (!analyticsData) return null;

  const COLORS = ['hsl(145, 65%, 42%)', 'hsl(28, 45%, 35%)', 'hsl(200, 75%, 55%)', 'hsl(45, 95%, 58%)'];

  // Generate trend data for time-series visualization
  const trendData = [
    { month: 'Jan', ecoScore: 72, co2Saved: 120, costSavings: 850 },
    { month: 'Feb', ecoScore: 74, co2Saved: 145, costSavings: 920 },
    { month: 'Mar', ecoScore: 78, co2Saved: 168, costSavings: 1050 },
    { month: 'Apr', ecoScore: 76, co2Saved: 155, costSavings: 980 },
    { month: 'May', ecoScore: 82, co2Saved: 192, costSavings: 1180 },
    { month: 'Jun', ecoScore: 85, co2Saved: 215, costSavings: 1350 },
  ];

  // Material usage distribution
  const usageData = packagingMaterials.slice(0, 6).map((m, i) => ({
    name: m.name,
    usage: Math.round(Math.random() * 30 + 10),
    fill: COLORS[i % COLORS.length],
  }));

  // Export functionality
  const handleExport = async (format: 'pdf' | 'excel') => {
    setIsExporting(format);
    
    // Simulate export processing
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    // Create export content
    const reportData = {
      title: 'EcoPackAI Sustainability Report',
      generatedAt: new Date().toISOString(),
      summary: {
        totalMaterials: packagingMaterials.length,
        avgBiodegradability: analyticsData.summaryMetrics.avgBiodegradability,
        avgRecyclability: analyticsData.summaryMetrics.avgRecyclability,
        co2ReductionPotential: analyticsData.summaryMetrics.avgCO2Reduction,
      },
      materials: packagingMaterials.map(m => ({
        name: m.name,
        biodegradability: m.biodegradability * 10,
        recyclability: m.recyclability,
        co2Impact: m.co2Impact,
        costPerUnit: m.costPerUnit,
        categories: m.suitableCategories.join(', '),
      })),
      categoryAnalysis: analyticsData.avgEcoScoreByCategory,
      trends: trendData,
    };

    if (format === 'pdf') {
      // Generate PDF-like content
      const pdfContent = `
ECOPACKAI SUSTAINABILITY REPORT
================================
Generated: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY
-----------------
Total Eco-Friendly Materials Analyzed: ${reportData.summary.totalMaterials}
Average Biodegradability: ${reportData.summary.avgBiodegradability}%
Average Recyclability: ${reportData.summary.avgRecyclability}%
CO₂ Reduction vs Traditional: ${reportData.summary.co2ReductionPotential}%

MATERIAL ANALYSIS
-----------------
${reportData.materials.map(m => `
${m.name}
  - Biodegradability: ${m.biodegradability}%
  - Recyclability: ${m.recyclability}%
  - CO₂ Impact: ${m.co2Impact} kg
  - Cost: $${m.costPerUnit.toFixed(2)}/unit
  - Suitable for: ${m.categories}
`).join('')}

CATEGORY PERFORMANCE
--------------------
${reportData.categoryAnalysis.map(c => `${c.category}: ${c.avgScore} avg eco-score`).join('\n')}

SUSTAINABILITY TRENDS
---------------------
${trendData.map(t => `${t.month}: Eco Score ${t.ecoScore}, CO₂ Saved ${t.co2Saved}kg, Savings $${t.costSavings}`).join('\n')}

---
Report generated by EcoPackAI - AI-Powered Sustainable Packaging Recommendation System
      `;
      
      const blob = new Blob([pdfContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'EcoPackAI_Sustainability_Report.txt';
      a.click();
      URL.revokeObjectURL(url);
    } else {
      // Generate CSV/Excel-like content
      const headers = ['Material Name', 'Biodegradability %', 'Recyclability %', 'CO₂ Impact (kg)', 'Cost per Unit ($)', 'Suitable Categories'];
      const rows = reportData.materials.map(m => [
        m.name,
        m.biodegradability,
        m.recyclability,
        m.co2Impact,
        m.costPerUnit.toFixed(2),
        m.categories,
      ]);
      
      const csvContent = [
        'EcoPackAI Sustainability Report',
        `Generated: ${new Date().toLocaleDateString()}`,
        '',
        'SUMMARY',
        `Total Materials,${reportData.summary.totalMaterials}`,
        `Avg Biodegradability,${reportData.summary.avgBiodegradability}%`,
        `Avg Recyclability,${reportData.summary.avgRecyclability}%`,
        `CO₂ Reduction,${reportData.summary.co2ReductionPotential}%`,
        '',
        'MATERIALS DATA',
        headers.join(','),
        ...rows.map(row => row.join(',')),
        '',
        'CATEGORY ANALYSIS',
        'Category,Average Eco Score',
        ...reportData.categoryAnalysis.map(c => `${c.category},${c.avgScore}`),
        '',
        'MONTHLY TRENDS',
        'Month,Eco Score,CO₂ Saved (kg),Cost Savings ($)',
        ...trendData.map(t => `${t.month},${t.ecoScore},${t.co2Saved},${t.costSavings}`),
      ].join('\n');
      
      const blob = new Blob([csvContent], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'EcoPackAI_Report.csv';
      a.click();
      URL.revokeObjectURL(url);
    }
    
    setIsExporting(null);
    
    // Show email notification toast
    toast.success('Report sent to your email', {
      description: `Your ${format.toUpperCase()} sustainability report has been generated and sent.`,
      icon: <Mail className="h-4 w-4" />,
    });
  };

  const MetricCard = ({ 
    icon: Icon, 
    title, 
    value, 
    suffix, 
    color,
    trend,
  }: { 
    icon: React.ElementType; 
    title: string; 
    value: number | string; 
    suffix?: string;
    color: string;
    trend?: { value: number; positive: boolean };
  }) => (
    <div className="eco-card">
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm text-muted-foreground mb-1">{title}</p>
          <p className="text-3xl font-bold text-foreground">
            {value}
            <span className="text-lg text-muted-foreground ml-1">{suffix}</span>
          </p>
          {trend && (
            <div className={`flex items-center gap-1 mt-1 text-xs ${trend.positive ? 'text-eco-leaf' : 'text-destructive'}`}>
              <TrendingUp className={`w-3 h-3 ${!trend.positive && 'rotate-180'}`} />
              <span>{trend.positive ? '+' : ''}{trend.value}% vs last month</span>
            </div>
          )}
        </div>
        <div className="w-12 h-12 rounded-xl flex items-center justify-center" style={{ backgroundColor: `${color}20` }}>
          <Icon className="w-6 h-6" style={{ color }} />
        </div>
      </div>
    </div>
  );

  return (
    <section id="dashboard" className="py-20 bg-secondary/30">
      <div className="container mx-auto px-4">
        <div className="max-w-7xl mx-auto">
          {/* Section Header */}
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-8">
            <div>
              <div className="inline-flex items-center gap-2 eco-badge mb-4">
                <BarChart3 className="w-4 h-4" />
                <span>Task 7: BI Dashboard & Analytics</span>
              </div>
              <h2 className="text-3xl sm:text-4xl font-display font-bold text-foreground mb-2">
                Business Intelligence Overview
              </h2>
              <p className="text-muted-foreground">
                Real-time analytics, performance metrics, and sustainability insights
              </p>
            </div>
            
            {/* Export Buttons */}
            <div className="flex gap-3">
              <Button 
                variant="outline" 
                onClick={() => handleExport('pdf')}
                disabled={isExporting !== null}
              >
                {isExporting === 'pdf' ? (
                  <div className="w-4 h-4 border-2 border-current/30 border-t-current rounded-full animate-spin" />
                ) : (
                  <FileText className="w-4 h-4" />
                )}
                Export PDF
              </Button>
              <Button 
                variant="outline"
                onClick={() => handleExport('excel')}
                disabled={isExporting !== null}
              >
                {isExporting === 'excel' ? (
                  <div className="w-4 h-4 border-2 border-current/30 border-t-current rounded-full animate-spin" />
                ) : (
                  <FileSpreadsheet className="w-4 h-4" />
                )}
                Export Excel
              </Button>
            </div>
          </div>

          {/* KPI Cards */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
            <MetricCard 
              icon={Leaf} 
              title="Avg. Biodegradability" 
              value={analyticsData.summaryMetrics.avgBiodegradability} 
              suffix="%"
              color="hsl(145, 65%, 42%)"
              trend={{ value: 3.2, positive: true }}
            />
            <MetricCard 
              icon={Recycle} 
              title="Avg. Recyclability" 
              value={analyticsData.summaryMetrics.avgRecyclability} 
              suffix="%"
              color="hsl(200, 75%, 55%)"
              trend={{ value: 1.8, positive: true }}
            />
            <MetricCard 
              icon={TrendingDown} 
              title="CO₂ Reduction" 
              value={analyticsData.summaryMetrics.avgCO2Reduction} 
              suffix="%"
              color="hsl(28, 45%, 35%)"
              trend={{ value: 5.4, positive: true }}
            />
            <MetricCard 
              icon={Package} 
              title="Materials Available" 
              value={analyticsData.summaryMetrics.materialCount} 
              suffix=""
              color="hsl(45, 95%, 58%)"
            />
          </div>

          {/* Charts Grid */}
          <div className="grid lg:grid-cols-2 gap-6">
            {/* Sustainability Trend Chart */}
            <div className="eco-card lg:col-span-2">
              <h3 className="text-lg font-semibold text-foreground mb-6 flex items-center gap-2">
                <Calendar className="w-5 h-5 text-eco-leaf" />
                Sustainability Performance Trends
              </h3>
              <div className="h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={trendData}>
                    <defs>
                      <linearGradient id="colorEco" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="hsl(145, 65%, 42%)" stopOpacity={0.3}/>
                        <stop offset="95%" stopColor="hsl(145, 65%, 42%)" stopOpacity={0}/>
                      </linearGradient>
                      <linearGradient id="colorCO2" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="hsl(200, 75%, 55%)" stopOpacity={0.3}/>
                        <stop offset="95%" stopColor="hsl(200, 75%, 55%)" stopOpacity={0}/>
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                    <XAxis 
                      dataKey="month" 
                      tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }}
                    />
                    <YAxis 
                      tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }}
                    />
                    <Tooltip 
                      contentStyle={{ 
                        backgroundColor: 'hsl(var(--card))', 
                        border: '1px solid hsl(var(--border))',
                        borderRadius: '8px'
                      }}
                    />
                    <Legend />
                    <Area 
                      type="monotone" 
                      dataKey="ecoScore" 
                      name="Eco Score"
                      stroke="hsl(145, 65%, 42%)" 
                      fillOpacity={1}
                      fill="url(#colorEco)"
                    />
                    <Area 
                      type="monotone" 
                      dataKey="co2Saved" 
                      name="CO₂ Saved (kg)"
                      stroke="hsl(200, 75%, 55%)" 
                      fillOpacity={1}
                      fill="url(#colorCO2)"
                    />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* CO2 Comparison Chart */}
            <div className="eco-card">
              <h3 className="text-lg font-semibold text-foreground mb-6 flex items-center gap-2">
                <TrendingDown className="w-5 h-5 text-eco-leaf" />
                CO₂ Impact: Eco vs Traditional
              </h3>
              <div className="h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={analyticsData.co2ComparisonData} barCategoryGap="20%">
                    <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                    <XAxis 
                      dataKey="name" 
                      tick={{ fontSize: 10, fill: 'hsl(var(--muted-foreground))' }}
                      angle={-45}
                      textAnchor="end"
                      height={80}
                    />
                    <YAxis 
                      tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }}
                      label={{ value: 'kg CO₂', angle: -90, position: 'insideLeft', fontSize: 12 }}
                    />
                    <Tooltip 
                      contentStyle={{ 
                        backgroundColor: 'hsl(var(--card))', 
                        border: '1px solid hsl(var(--border))',
                        borderRadius: '8px'
                      }}
                    />
                    <Legend />
                    <Bar dataKey="co2Impact" name="Eco Material" fill="hsl(145, 65%, 42%)" radius={[4, 4, 0, 0]} />
                    <Bar dataKey="traditional" name="Traditional Plastic" fill="hsl(0, 0%, 70%)" radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Cost Analysis Chart */}
            <div className="eco-card">
              <h3 className="text-lg font-semibold text-foreground mb-6 flex items-center gap-2">
                <DollarSign className="w-5 h-5 text-eco-earth" />
                Cost Comparison Analysis
              </h3>
              <div className="h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={analyticsData.costAnalysisData} barCategoryGap="20%">
                    <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                    <XAxis 
                      dataKey="name" 
                      tick={{ fontSize: 10, fill: 'hsl(var(--muted-foreground))' }}
                      angle={-45}
                      textAnchor="end"
                      height={80}
                    />
                    <YAxis 
                      tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }}
                      label={{ value: 'USD', angle: -90, position: 'insideLeft', fontSize: 12 }}
                    />
                    <Tooltip 
                      contentStyle={{ 
                        backgroundColor: 'hsl(var(--card))', 
                        border: '1px solid hsl(var(--border))',
                        borderRadius: '8px'
                      }}
                      formatter={(value: number) => [`$${value.toFixed(2)}`, '']}
                    />
                    <Legend />
                    <Bar dataKey="eco" name="Eco Material" fill="hsl(28, 45%, 35%)" radius={[4, 4, 0, 0]} />
                    <Bar dataKey="traditional" name="Traditional" fill="hsl(0, 0%, 70%)" radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Performance Radar */}
            <div className="eco-card">
              <h3 className="text-lg font-semibold text-foreground mb-6 flex items-center gap-2">
                <Leaf className="w-5 h-5 text-eco-sky" />
                Material Performance Overview
              </h3>
              <div className="h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <RadarChart data={analyticsData.materialPerformanceData.slice(0, 6)}>
                    <PolarGrid stroke="hsl(var(--border))" />
                    <PolarAngleAxis 
                      dataKey="name" 
                      tick={{ fontSize: 9, fill: 'hsl(var(--muted-foreground))' }}
                    />
                    <PolarRadiusAxis tick={{ fontSize: 10, fill: 'hsl(var(--muted-foreground))' }} />
                    <Radar 
                      name="Biodegradability" 
                      dataKey="biodegradability" 
                      stroke="hsl(145, 65%, 42%)" 
                      fill="hsl(145, 65%, 42%)" 
                      fillOpacity={0.3} 
                    />
                    <Radar 
                      name="Recyclability" 
                      dataKey="recyclability" 
                      stroke="hsl(200, 75%, 55%)" 
                      fill="hsl(200, 75%, 55%)" 
                      fillOpacity={0.3} 
                    />
                    <Legend />
                  </RadarChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Material Usage Pie Chart */}
            <div className="eco-card">
              <h3 className="text-lg font-semibold text-foreground mb-6 flex items-center gap-2">
                <Package className="w-5 h-5 text-eco-sun" />
                Material Usage Distribution
              </h3>
              <div className="h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={usageData}
                      cx="50%"
                      cy="50%"
                      innerRadius={50}
                      outerRadius={90}
                      paddingAngle={3}
                      dataKey="usage"
                      nameKey="name"
                      label={({ name, percent }) => `${name.split(' ')[0]} ${(percent * 100).toFixed(0)}%`}
                      labelLine={false}
                    >
                      {usageData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.fill} />
                      ))}
                    </Pie>
                    <Tooltip 
                      contentStyle={{ 
                        backgroundColor: 'hsl(var(--card))', 
                        border: '1px solid hsl(var(--border))',
                        borderRadius: '8px'
                      }}
                      formatter={(value: number) => [`${value}% usage`, '']}
                    />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>

          {/* Insights Panel */}
          <div className="mt-8 grid md:grid-cols-3 gap-4">
            <div className="eco-card border-eco-leaf/20">
              <h4 className="font-semibold text-foreground mb-2">Environmental Impact</h4>
              <p className="text-sm text-muted-foreground">
                Eco-friendly materials show an average of <strong className="text-eco-leaf">{analyticsData.summaryMetrics.avgCO2Reduction}% lower</strong> carbon 
                footprint compared to traditional plastic packaging alternatives.
              </p>
            </div>
            <div className="eco-card border-eco-earth/20">
              <h4 className="font-semibold text-foreground mb-2">Cost Considerations</h4>
              <p className="text-sm text-muted-foreground">
                While initial costs may be higher, sustainable materials offer <strong className="text-eco-earth">long-term value</strong> through 
                reduced waste disposal fees and enhanced brand perception.
              </p>
            </div>
            <div className="eco-card border-eco-sky/20">
              <h4 className="font-semibold text-foreground mb-2">Recyclability Metrics</h4>
              <p className="text-sm text-muted-foreground">
                Our curated materials achieve an average recyclability rate of <strong className="text-eco-sky">{analyticsData.summaryMetrics.avgRecyclability}%</strong>, 
                significantly exceeding industry standards.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
